/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'productCount' : IDL.Nat,
  'image' : IDL.Text,
});
export const ProductVariant = IDL.Record({
  'name' : IDL.Text,
  'priceInPaise' : IDL.Nat,
  'stock' : IDL.Nat,
  'variantId' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'categories' : IDL.Vec(IDL.Text),
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'unit' : IDL.Text,
  'priceInPaise' : IDL.Nat,
  'description' : IDL.Text,
  'volume' : IDL.Text,
  'variants' : IDL.Vec(ProductVariant),
  'stock' : IDL.Nat,
  'brand' : IDL.Text,
  'image' : IDL.Text,
  'hasDealPrice' : IDL.Bool,
  'dealPriceInPaise' : IDL.Opt(IDL.Nat),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CartItem = IDL.Record({
  'id' : IDL.Nat,
  'quantity' : IDL.Nat,
  'variant' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCategory' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'createProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'getAllCategoriesByProductCount' : IDL.Func(
      [],
      [IDL.Vec(Category)],
      ['query'],
    ),
  'getAllProductsByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllProductsByStock' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFilteredProductsByCategory' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeDemoData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([IDL.Vec(CartItem)], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'productCount' : IDL.Nat,
    'image' : IDL.Text,
  });
  const ProductVariant = IDL.Record({
    'name' : IDL.Text,
    'priceInPaise' : IDL.Nat,
    'stock' : IDL.Nat,
    'variantId' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'categories' : IDL.Vec(IDL.Text),
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'unit' : IDL.Text,
    'priceInPaise' : IDL.Nat,
    'description' : IDL.Text,
    'volume' : IDL.Text,
    'variants' : IDL.Vec(ProductVariant),
    'stock' : IDL.Nat,
    'brand' : IDL.Text,
    'image' : IDL.Text,
    'hasDealPrice' : IDL.Bool,
    'dealPriceInPaise' : IDL.Opt(IDL.Nat),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CartItem = IDL.Record({
    'id' : IDL.Nat,
    'quantity' : IDL.Nat,
    'variant' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCategory' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'createProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'getAllCategoriesByProductCount' : IDL.Func(
        [],
        [IDL.Vec(Category)],
        ['query'],
      ),
    'getAllProductsByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllProductsByStock' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFilteredProductsByCategory' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeDemoData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([IDL.Vec(CartItem)], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };