/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem {
  'id' : bigint,
  'quantity' : bigint,
  'variant' : [] | [bigint],
}
export interface Category {
  'id' : bigint,
  'name' : string,
  'productCount' : bigint,
  'image' : string,
}
export interface Product {
  'id' : bigint,
  'categories' : Array<string>,
  'inStock' : boolean,
  'name' : string,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'unit' : string,
  'priceInPaise' : bigint,
  'description' : string,
  'volume' : string,
  'variants' : Array<ProductVariant>,
  'stock' : bigint,
  'brand' : string,
  'image' : string,
  'hasDealPrice' : boolean,
  'dealPriceInPaise' : [] | [bigint],
}
export interface ProductVariant {
  'name' : string,
  'priceInPaise' : bigint,
  'stock' : bigint,
  'variantId' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCategory' : ActorMethod<[string, string], bigint>,
  'createProduct' : ActorMethod<
    [
      string,
      string,
      bigint,
      bigint,
      string,
      Array<string>,
      string,
      string,
      string,
    ],
    bigint
  >,
  'getAllCategoriesByProductCount' : ActorMethod<[], Array<Category>>,
  'getAllProductsByPrice' : ActorMethod<[], Array<Product>>,
  'getAllProductsByStock' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFilteredProductsByCategory' : ActorMethod<
    [string, string],
    Array<Product>
  >,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeDemoData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[Array<CartItem>], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];